# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveLocationTacker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LiveLocationTacker
  pod 'SwiftGen'#, '~> 6.6'
  
  pod 'Toast-Swift'
  pod 'ReachabilitySwift'
  pod 'ProgressHUD'
  pod "UIViewUseful"
  pod 'SideMenuSwift'
  pod 'Kingfisher'
  pod 'NVActivityIndicatorView'
  pod 'IQKeyboardManagerSwift'
  pod 'lottie-ios'
  pod 'SKCountryPicker'
  pod 'PhoneNumberKit' , '~> 3.7'
  pod 'AEOTPTextField'
  
  pod 'Firebase', '~> 11.15'
  pod 'FirebaseAuth', '~> 11.15'
  pod 'FirebaseMessaging', '~> 11.15'
  pod 'FirebaseCrashlytics', '~> 11.15'
  pod 'FirebaseAnalytics', '~> 11.15'
  pod 'FirebaseDatabase', '~> 11.15'
  pod 'FirebaseStorage', '~> 11.15'
  
  pod 'SwiftJWT'
  pod 'RevenueCat'
  
  
  post_install do |installer|
      installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
              end
          end
      end
  end
end
